<?php
	session_start();
	session_destroy();
	unset($loginname);
	setcookie("member_login","",time()-3600);
	setcookie("member_password","",time()-3600);
	header("Location:index.php");
    exit;
?>